---
- name: remove_docker_container {{ docker_container_vaultwarden_name }}
  community.general.docker_container: 
    name: "{{ docker_container_vaultwarden_name }}"    
    container_default_behavior: no_defaults
    keep_volumes: "{{ docker_container_vaultwarden_keep_volumes | default('yes') }}"
    state: absent

- name: remove_docker_network {{ docker_network_vaultwarden_name }}
  community.general.docker_network:
    name: "{{ docker_network_vaultwarden_name }}"
    force: yes
    state: absent
