---
# tasks file for ansible-role-docker-container-vaultwarden

- name: docker_image pull {{ docker_image_vaultwarden_name }}
  community.docker.docker_image:
    name: '{{ docker_image_vaultwarden_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_vaultwarden_pull

- name: docker_network {{ docker_container_vaultwarden_name }}
  community.docker.docker_network:
    name: "{{ docker_network_vaultwarden_name }}"
    driver: "{{ docker_network_vaultwarden_driver | default('bridge') }}"
    attachable: "{{ docker_network_vaultwarden_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_vaultwarden_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_vaultwarden_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_vaultwarden_name }}
  community.docker.docker_container:
    name: "{{ docker_container_vaultwarden_name }}"
    comparisons: "{{ docker_container_vaultwarden_comparisons }}"
    image: "{{ docker_container_vaultwarden_image }}"
    state: "{{ docker_container_vaultwarden_state | default('started') }}"
    recreate: "{{ docker_container_vaultwarden_recreate | default(false) }}"
    restart: "{{ docker_container_vaultwarden_restart | default(false) }}"
    restart_policy: "{{ docker_container_vaultwarden_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_vaultwarden_auto_remove | default(false) }}"
    detach: "{{ docker_container_vaultwarden_detach | default(true) }}"
    init: "{{ docker_container_vaultwarden_init | default(false) }}"
    interactive: "{{ docker_container_vaultwarden_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_vaultwarden_keep_volumes | default(true) }}"
    memory: "{{ docker_container_vaultwarden_memory | default('0') }}"
    paused: "{{ docker_container_vaultwarden_paused | default(false) }}"
    privileged: "{{ docker_container_vaultwarden_privileged | default(false) }}"
    read_only: "{{ docker_container_vaultwarden_read_only | default(false) }}"
    tty: "{{ docker_container_vaultwarden_tty | default(false) }}"
    env_file: "{{ docker_container_vaultwarden_env_file | default(omit) }}"
    env: "{{ docker_container_vaultwarden_env | default(omit) }}"
    volumes: "{{ docker_container_vaultwarden_volumes | default(omit) }}"
    labels: "{{ docker_container_vaultwarden_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_vaultwarden_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_vaultwarden_name }}"
    pull: "{{ docker_container_vaultwarden_pull | default(false) }}"
    networks: "{{ docker_container_vaultwarden_networks }}"
    published_ports: "{{ docker_container_vaultwarden_ports | default(omit) }}"
